name: CD – Build & Push Docker image

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # Push in GitHub Container Registry

    steps:
    - uses: actions/checkout@v4

    # Repo-Namen in Kleinbuchstaben wandeln (GHCR verlangt das)
    - name: Prepare image name
      id: prep
      run: echo "image=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build JAR
      run: mvn -B clean package

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ steps.prep.outputs.image }}:${{ github.sha }}
          ghcr.io/${{ steps.prep.outputs.image }}:latest
